# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\Create_Project_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create_Project_Interface(object):
    def setupUi(self, Create_Project_Interface):
        Create_Project_Interface.setObjectName("Create_Project_Interface")
        Create_Project_Interface.resize(480, 504)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Create_Project_Interface.sizePolicy().hasHeightForWidth())
        Create_Project_Interface.setSizePolicy(sizePolicy)
        Create_Project_Interface.setMinimumSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setPointSize(10)
        Create_Project_Interface.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui_files\\../icons/addixo_X_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Create_Project_Interface.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Create_Project_Interface)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.Quit_CreateProject_Interface = QtWidgets.QPushButton(Create_Project_Interface)
        self.Quit_CreateProject_Interface.setMinimumSize(QtCore.QSize(111, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui_files\\../icons/icons8-annuler-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Quit_CreateProject_Interface.setIcon(icon1)
        self.Quit_CreateProject_Interface.setObjectName("Quit_CreateProject_Interface")
        self.gridLayout.addWidget(self.Quit_CreateProject_Interface, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 7, 1, 1)
        self.label = QtWidgets.QLabel(Create_Project_Interface)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.Save_ProjectName = QtWidgets.QPushButton(Create_Project_Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save_ProjectName.sizePolicy().hasHeightForWidth())
        self.Save_ProjectName.setSizePolicy(sizePolicy)
        self.Save_ProjectName.setMinimumSize(QtCore.QSize(111, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui_files\\../icons/icons8-coche-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save_ProjectName.setIcon(icon2)
        self.Save_ProjectName.setObjectName("Save_ProjectName")
        self.gridLayout.addWidget(self.Save_ProjectName, 2, 6, 1, 1)
        self.Project_Name_field = QtWidgets.QLineEdit(Create_Project_Interface)
        self.Project_Name_field.setObjectName("Project_Name_field")
        self.gridLayout.addWidget(self.Project_Name_field, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(Create_Project_Interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(700, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\ui_files\\../icons/addixo_X_icon.ico"))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)

        self.retranslateUi(Create_Project_Interface)
        QtCore.QMetaObject.connectSlotsByName(Create_Project_Interface)

    def retranslateUi(self, Create_Project_Interface):
        _translate = QtCore.QCoreApplication.translate
        Create_Project_Interface.setWindowTitle(_translate("Create_Project_Interface", "Frame"))
        self.Quit_CreateProject_Interface.setText(_translate("Create_Project_Interface", "Quit"))
        self.label.setText(_translate("Create_Project_Interface", "Project Name :"))
        self.Save_ProjectName.setText(_translate("Create_Project_Interface", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Create_Project_Interface = QtWidgets.QFrame()
    ui = Ui_Create_Project_Interface()
    ui.setupUi(Create_Project_Interface)
    Create_Project_Interface.show()
    sys.exit(app.exec_())
